### ISSUE TITLE
finetune results

### ISSUE THREAD

**Issue by Katherinaxxx** [jiachenwestlake/Entity_BERT#1]
hi, thanks for your job!
I download your pre-trained BERT weights (news) and fine-tune on NER task. BUT i got f1=r=p=0
Do you have any idea?

**Comment by yuefeng-shi** [comment]
Hello, thanks for your comment.
I download the code and weights from Github and rerun the fine-tune task(news), but I get the normal result with (P72.4405_R81.4047_F76.6614) . So can you upload coding logs if you still have the problem?

**Comment by Katherinaxxx** [comment]
Thanks!
I fixed the problem by changing data_load.py line119
`entries = codecs.open(fpath, 'r', encoding= 'utf-8').read().strip().split("\n\n")`
into
`entries = codecs.open(fpath, 'r', encoding= 'utf-8').read().strip().split("\r\n\r\n")`

**Comment by yuefeng-shi** [comment]
OK thanks
