### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'batch_step'

### ISSUE THREAD

**Issue by LuWei091997** [jiachenwestlake/Entity_BERT#3]
您好，在运行train.py的时候提示AttributeError: 'NoneType' object has no attribute 'batch_step'，想请问一下怎么修正。

01/24/2021 11:43:41 - INFO - utils.tokenization -   loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at C:\Users\z1486\.pytorch_pretrained_bert\26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
Traceback (most recent call last):
  File "F:/LectureArtical/Entity-BERT/Entity_BERT-master/train.py", line 143, in <module>
    total_train_steps = int(train_iter.batch_step * args.num_train_epochs)
AttributeError: 'NoneType' object has no attribute 'batch_step'

**Comment by yuefeng-shi** [comment]
The original code in train.py line 143 should be
total_train_steps = int(train_iter.batch_steps * args.num_train_epochs)
it is "batch_steps", not "batch_step"
